name: RankingPlugin
version: 1.0.0
main: com.nextplugins.libs.npcranking.example.RankPlugin
author: eikefab
depend:
  - ProtocolLib
softdepend:
  - HolographicDisplays
  - DecentHolograms
commands:
  npcposition:
    description: "Save NPC position for further usage."